# workflow for re-running publishing to NPM in case it fails for some reason
name: Publish NPM
on:
  push:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Publish to NPM
        run: |
          bash .bin/publish_npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
